(lang dune 3.4)

(name stramon)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Stramon developers")

(maintainers "Darren Ldl")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name stramon)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
